# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: yinzhang <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/10/17 12:25:44 by yinzhang          #+#    #+#              #
#    Updated: 2019/10/17 12:25:46 by yinzhang         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM ubuntu

RUN apt-get update
RUN apt-get install telnet -y

ENTRYPOINT telnet towel.blinkenlights.nl


